# 雷达型号选择: N10, N10_P
lidar_name: N10

# 定义 base_link -> laser_link 的固定 TF 变换，单位cm和度
x: 0
y: 0
z: 10
roll: 0
pitch: 0
yaw: 0

# SLAM_TOOLBOX建图or定位模式，mapping/localization
mode: mapping

# 手动修改参数，不可由上位机修改

# 雷达数据发布的话题
scan_topic: /scan_raw

# 雷达串口设备,不可设置
serial_port_: /dev/usb_robot

# SLAM_TOOLBOX异步or同步模式，async/async
sync_async: async
